minerals/urls.py
from django.urls import re_path

from . import views

app_name = 'minerals'

urlpatterns = [
    re_path(r'(?P<pk>\d+)/$', views.mineral_detail, name='detail')
]

minerals_catalog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views


urlpatterns = [
    re_path(r'^minerals/', include('minerals.urls', namespace='minerals')),
    path('admin/', admin.site.urls),
    re_path(r'^$', views.index, name='home'),
]

urlpatterns += staticfiles_urlpatterns()

minerals/models.py
from django.db import models
import json

# Create your models here.

class Mineral(models.Model):
    '''Mineral class for all minerals'''
    name = models.CharField(max_length=100, unique=True)
    image_filename = models.CharField(max_length=255)
    image_caption = models.CharField(max_length=255)
    category = models.CharField(max_length=255)
    formula = models.CharField(max_length=255)
    strunz_classification = models.CharField(max_length=255)
    crystal_system = models.CharField(max_length=255)
    unit_cell = models.CharField(max_length=255)
    color = models.CharField(max_length=255)
    crystal_symmetry = models.CharField(max_length=255)
    cleavage = models.CharField(max_length=255)
    mohs_scale_hardness = models.CharField(max_length=255)
    luster = models.CharField(max_length=255)
    streak = models.CharField(max_length=255)
    diaphaneity = models.CharField(max_length=255)
    optical_properties = models.CharField(max_length=255)
    refractive_index = models.CharField(max_length=755)
    crystal_habit = models.CharField(max_length=255)
    specific_gravity = models.CharField(max_length=255)
    group = models.CharField(max_length=255)

    class Meta:
        ordering = ['name',]

    def __str__(self):
        return self.name

minerals/views.py
from django.shortcuts import render, get_object_or_404
from .models import Mineral
import random

# Create your views here.
 
def mineral_detail(request, pk):
    '''Detail view for mineral by primary key (pk)'''
    mineral = get_object_or_404(Mineral, pk=pk)
    random_mineral = random.choice(Mineral.objects.all())
    return render(request, 'minerals/mineral_detail.html',
        {'mineral': mineral, 'random_mineral': random_mineral})

minerals_catalog/views.py
from django.shortcuts import render

from minerals.models import Mineral
import random


def index(request):
    '''Home page displaying all minerals'''
    minerals = Mineral.objects.all()
    random_mineral = random.choice(minerals)
    return render(request, 'index.html', {'minerals': minerals,'random_mineral': random_mineral})

minerals/templates/minerals/mineral_detail.html
{% extends 'layout.html' %}
{% load static %}

{% block title %} {{ block.super }}|{{ mineral.name }} {% endblock %}


{% block content %}

    <div class="grid-100 mineral__container">
      <h1 class="mineral__name">{{ mineral.name|title }}</h1>
      <div class="mineral__image-bg">
        <img class="mineral__image" src="{% static 'images' %}/{{ mineral.name }}.jpg" alt="{{ mineral.name|title }}">
        <p class="mineral__caption">{{ mineral.image_caption|title }}</p>
      </div>

<div class="mineral__table-container">

        <table class="mineral__table">
          <tr>
            <td class="mineral__category">Category</td>
            <td>{{ mineral.category|title }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Formula</td>
            <td class="mineral__formula">{{ mineral.formula|safe }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Strunz Classification</td>
            <td>{{ mineral.strunz_classification|title }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Unit Cell</td>
            <td>{{ mineral.unit_cell }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Color</td>
            <td>{{ mineral.color|title }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Crystal Habit</td>
            <td>{{ mineral.crystal_habit|title }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Mohs Scale Hardness</td>
            <td>{{ mineral.mohs_scale_hardness }}</td>
          </tr>
            <tr>
            <td class="mineral__category">Group</td>
            <td>{{ mineral.group|title }}</td>
          </tr>
        </table>
      </div>
    </div>
{% endblock %}

{% block random_mineral %}
    <div class="minerals__random">
    <a class="minerals__anchor" href="{% url 'minerals:detail' pk=random_mineral.pk  %}">Show random mineral</a>
  </div>
{% endblock %}

minerals/templates/minerals/mineral_group_nav.html
{% load static from staticfiles %}

<p><i>There are {{ group_count }} mineral group{{group_count|pluralize}} on this site!</i> </p>

templates/index.html
{% extends 'layout.html' %}

{% block content %}
<div class="grid-100">
      <ul class="minerals__container">

          {% for mineral in minerals %}
        <li class="minerals__item">
          <a class="minerals__anchor" href="{% url 'minerals:detail' pk=mineral.pk  %}">{{ mineral.name }}</a>
        </li>
          {% endfor %}

      </ul>
</div>
{% endblock %}

{% block random_mineral %}
    <div class="minerals__random">
    <a class="minerals__anchor" href="{% url 'minerals:detail' pk=random_mineral.pk  %}">Show random mineral</a>
  </div>
{% endblock %}

templates/layout.html
{% load static from staticfiles %}
{% load mineral_extras %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
    <title>Mike's Minerals Catalog {% block title %}{% endblock %}</title>
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="{% static 'css/global.css' %}">
</head>
<body>
  <div class="bounds">
    <div class="grid-100">
      <a href="/">
        <svg class="logo" viewBox="0 0 127.6 84.8" preserveAspectRation="xMinYMin meet">
          <polygon points="42.7,84.8 49.6,79.4 40,62.5 51.2,43.5 51.2,43.5 25,0 0,55.6 "/>
          <polygon class="logo--middle" points="52.9,79.5 52.9,79.5 84.8,80.1 59.7,35 43.3,62.4 "/>
          <polygon points="127.6,61.4 127.6,61.4 110.3,13.5 110.3,13.5 70.3,48.1 70.3,48.1 88.3,80.5 95.3,81.4 95.3,81.4 "/>
        </svg>
        <h1 class="logo__name text-centered">Mike's Minerals</h1>
      </a>
      <p class="logo__text text-centered">They're not rocks!</p>
    </div>
    {% block content %}{% endblock %}
      {% nav_group_list %}
  </div>

  {% block random_mineral %}{% endblock %}
</body>
</html>